// Mocks generated by Mockito 5.3.2 from annotations
// in algovisualizer/test/repository/visualizer_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:algovisualizer/data/data_source/local_data_source.dart' as _i3;
import 'package:algovisualizer/domain/entity/algoritm_model.dart' as _i4;
import 'package:algovisualizer/domain/entity/visualizer.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeVisualizer_0 extends _i1.SmartFake implements _i2.Visualizer {
  _FakeVisualizer_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [LocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalDataSource extends _i1.Mock implements _i3.LocalDataSource {
  MockLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.AlgorithmModel? getDataAlgorithmVisualizer(String? keyName) =>
      (super.noSuchMethod(Invocation.method(
        #getDataAlgorithmVisualizer,
        [keyName],
      )) as _i4.AlgorithmModel?);
  @override
  _i2.Visualizer generatedUnSortData(int? maxItem) => (super.noSuchMethod(
        Invocation.method(
          #generatedUnSortData,
          [maxItem],
        ),
        returnValue: _FakeVisualizer_0(
          this,
          Invocation.method(
            #generatedUnSortData,
            [maxItem],
          ),
        ),
      ) as _i2.Visualizer);
}
